# Development process support.

name: dev

on:
  push:
    branches:
      - "**"
      - "!gh-readonly-queue/**"
  merge_group:
  schedule:
    - cron: "0 20 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'merge_group' }}

defaults:
  run:
    shell: bash

env:
  RUSTDOCFLAGS: "-D warnings"

jobs:
  code:
    uses: ./.github/workflows/partial-code.yml
    secrets: inherit
    permissions:
      contents: read

  build:
    uses: ./.github/workflows/partial-build.yml
    secrets: inherit
    permissions:
      contents: write

  docker:
    uses: ./.github/workflows/partial-docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
