on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-24.04
    timeout-minutes: 50
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for main
        id: meta-main
        uses: docker/metadata-action@v5
        with:
          bake-target: docker-metadata-action-main
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}-main
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          allow: ssh
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-main.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
